### ISSUE TITLE
px4 or ardupilot firmware used in the flight experiments?

### ISSUE THREAD

**Issue by GChasing** [HKUST-Aerial-Robotics/AutoTrans#2]
I'm wonder which firmware are you used in the flight experiments? In the related paper, it  seems that the ardupilot(APM) firmware is used. Another issue is that, the attitude and the position for the payload are obtained via the mocap?

Looking for your reply and thanks in advance.

**Comment by li-haojia** [comment]
Yes, we use the Ardupilot as the flight controller firmware (4.3.1). It has the Bi-Directional DSHOT which can provide the rotor speed info (RPM). In our experiment, the attitude and the position of the payload are obtained by Mocap. You can also obtain the cable direction by attaching an IMU to the cable. We also test this method, it is feasible.

**Comment by GChasing** [comment]
Thanks a lot. It is a great job!
