### ISSUE TITLE
mpc中是否缺少对无人机姿态四元数的约束

### ISSUE THREAD

**Issue by Zeen-x** [HKUST-Aerial-Robotics/AutoTrans#3]
姿态四元数有模长为1的约束，但是在`controller/payload_mpc_controller/model/quadrotor_payload_mpc_hybird.cpp`和`controller/payload_mpc_controller/model/quadrotor_payload_mpc_with_ext_force.cpp`的模型中好像没看到相关内容，会不会在运行过程中导致四元数不满足单位四元数约束.

**Comment by li-haojia** [comment]
实际上确实应该添加这个约束。但是我们发现，添加这个约束有时候会导致求解不稳定，因此在我们实际应用过程中就去掉。通常只要保证当前状态的四元数与reference的四元数是单位1，一般不会违背这个约束。更好的解决方法应该是在manifold上求解。
